project:
  type: website
  preview:
    port: 4311

website:
  title: "{funkyheatmap}"
  description: "Visualising data frames"
  site-url: https://funkyheatmap.github.io
  repo-url: https://github.com/funkyheatmap/funkyheatmap.github.io
  repo-actions: [edit, issue] 

  navbar:
    left:
      - href: index.qmd
        text: Home
      - features.qmd
      - text: Examples
        menu:
          - examples/dynbenchmark/index.qmd
          - examples/minimal/index.qmd
          - examples/mtcars/index.qmd
      - text: Paper
        href: paper/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto