project:
  type: website
  preview:
    port: 4311

website:
  title: ""
  description: "Visualising data frames"
  image: https://raw.githubusercontent.com/funkyheatmap/logo/refs/heads/main/src/funkyheatmap_edited.png
  site-url: https://funkyheatmap.github.io
  repo-url: https://github.com/funkyheatmap/funkyheatmap.github.io
  repo-actions: [edit, issue]
  open-graph:
    title: funkyheatmap - Visualising data frames
    image: https://raw.githubusercontent.com/funkyheatmap/logo/refs/heads/main/src/funkyheatmap_edited.png

  # navbar:
  #   logo: https://raw.githubusercontent.com/funkyheatmap/logo/refs/heads/main/src/funkyheatmap_edited.png
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - text: Implementations
  #       menu: 
  #         - href: https://www.npmjs.com/package/funkyheatmapjs
  #           text: JavaScript (incomplete)
  #         - href: https://funkyheatmap.github.io/funkyheatmappy
  #           text: Python
  #         - href: https://funkyheatmap.github.io/funkyheatmap
  #           text: R
  #   right:
  #     - icon: fab fa-github
  #       href: https://github.com/funkyheatmap/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto