on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up environment
        run: |
          echo "LINUX_VERSION=$(uname -rs)" >> $GITHUB_ENV

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: renv/python/virtualenvs/renv-python-3.10
          key: python-${{env.LINUX_VERSION}}-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
          restore-keys: python-${{env.LINUX_VERSION}}-${{ env.pythonLocation }}-

      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render with Quarto
        shell: bash -l {0}  
        run: |
          quarto render

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          force: false
          clean-exclude: pr-preview/
          token: ${{ secrets.GTHB_PAT }}

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
          token: ${{ secrets.GTHB_PAT }}
